"""antra migracija

Revision ID: 0d9b89087806
Revises: 80a97deb1efa
Create Date: 2023-03-28 21:38:01.305913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9b89087806'
down_revision = '80a97deb1efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Login',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_Login_name'),
    sa.UniqueConstraint('password', name='uq_Login_password')
    )
    # ### end Alembic commands ###
